/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package herbalsisteminventory;

import controller.DataBaseOperation;
import objekData.Pelanggan;


/**
 *
 * @author HP
 */
public class DataPelangganFrame extends javax.swing.JFrame {

    /**
     * Creates new form DataPelangganFrame
     */
    public DataPelangganFrame() {
        initComponents();
    }
    int angka;
    MainFrame windowMainFrame = null ;
    
    public void setMainFrame(MainFrame frameMasuk){
        windowMainFrame = frameMasuk ;
        
    }
    
        public void terimaData(Pelanggan dataMasuk, int noID) {
        namaDataPelangganBarTextField.setText(dataMasuk.getNama());
        membershipComboBox.setSelectedItem(dataMasuk.getMembership());
        noKTPPelangganBarTextField.setText(dataMasuk.getNoKTP()+ "");
        TglBuatPelangganBarTextField.setText(dataMasuk.getTglBuat()+ "");
        savePelangganButton.setText("Update");
        labelID.setText(noID+"");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        namaDataPelangganBarTextField = new javax.swing.JTextField();
        membershipComboBox = new javax.swing.JComboBox<>();
        noKTPPelangganBarTextField = new javax.swing.JTextField();
        TglBuatPelangganBarTextField = new javax.swing.JTextField();
        savePelangganButton = new javax.swing.JButton();
        labelID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Data Pelanggan (Baru)");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel2.setText("Nama :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel3.setText("Membership  :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel4.setText("No KTP :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel5.setText("Tgl Pembuatan :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        namaDataPelangganBarTextField.setText("......");
        getContentPane().add(namaDataPelangganBarTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 120, -1));

        membershipComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular", "Premium" }));
        getContentPane().add(membershipComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        noKTPPelangganBarTextField.setText("......");
        getContentPane().add(noKTPPelangganBarTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 120, -1));

        TglBuatPelangganBarTextField.setText("......");
        getContentPane().add(TglBuatPelangganBarTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 120, -1));

        savePelangganButton.setText("Save");
        savePelangganButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePelangganButtonActionPerformed(evt);
            }
        });
        getContentPane().add(savePelangganButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        labelID.setText("ID");
        getContentPane().add(labelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savePelangganButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePelangganButtonActionPerformed
        // TODO add your handling code here:
        Pelanggan pelangganBaru = new Pelanggan(); 
        pelangganBaru.setNama(namaDataPelangganBarTextField.getText());
        pelangganBaru.setMembership(membershipComboBox.getSelectedItem().toString());
        int noKTP = Integer.parseInt(noKTPPelangganBarTextField.getText());
        pelangganBaru.setNoKTP(noKTP);
        pelangganBaru.setTglBuat(TglBuatPelangganBarTextField.getText());

        
        DataBaseOperation engine = new DataBaseOperation();
        //engine.addDataPelanggan(pelangganBaru);
        
        //System.out.println("Data Berhasil Tersimpan");
        
        if (savePelangganButton.getText().equalsIgnoreCase("save")) {

       
            engine.addDataPelanggan(pelangganBaru);

            System.out.println("Data Berhasil Tersimpan");
        } else {
            
            int noID = Integer.parseInt(labelID.getText());
            
            engine.updateDataPelanggan(pelangganBaru,noID);

            System.out.println("Data Berhasil Terupdate");
        }
            
        windowMainFrame.refreshTabel();
        this.dispose();
        
    }//GEN-LAST:event_savePelangganButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataPelangganFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataPelangganFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataPelangganFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataPelangganFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataPelangganFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TglBuatPelangganBarTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel labelID;
    private javax.swing.JComboBox<String> membershipComboBox;
    private javax.swing.JTextField namaDataPelangganBarTextField;
    private javax.swing.JTextField noKTPPelangganBarTextField;
    private javax.swing.JButton savePelangganButton;
    // End of variables declaration//GEN-END:variables
}
