/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package herbalsisteminventory;

import controller.DataBaseOperation;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import objekData.Barang;
import objekData.Pelanggan;
import objekData.Penjualan;

/**
 *
 * @author HP
 */
public class DataPenjualanFrame extends javax.swing.JFrame {

    /**
     * Creates new form DataPenjualanFrame
     */
    
    MainFrame window = null;
    public void setMainFrame (MainFrame frameMasuk){
        window = frameMasuk;
        
    }
    
    public DataPenjualanFrame() {
        initComponents();

        DataBaseOperation engine = new DataBaseOperation();
        ArrayList<Barang> datadiperoleh = engine.getAllBarang();

        namaBarangComboBox.removeAllItems();

        for (int nomor = 0; nomor < datadiperoleh.size(); nomor++) {
            Barang barangdidapat = datadiperoleh.get(nomor);
            namaBarangComboBox.addItem(barangdidapat.getNama());
        }

    }
    
    public void terimaData(Penjualan dataMasuk, int noID) {
        namaBarangComboBox.setSelectedItem(dataMasuk.getNama());
        qtyBarangBaruTextField.setText(dataMasuk.getQty()+"");
        satuanBaruComboBox.setSelectedItem( dataMasuk.getSatuan());
        hargaBeliBarangBaruTextField.setText(dataMasuk.getHargaBeli() + "");
        hargaJualBarangBaruTextField.setText(dataMasuk.getHargaJual() + "");
        tglTransaksiTextFieldo.setText(dataMasuk.getTglTransaksi());
        saveBaranfBaruButton.setText("Update");
        labelID.setText(noID+"");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        qtyBarangBaruTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        satuanBaruComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        hargaBeliBarangBaruTextField = new javax.swing.JTextField();
        hargaJualBarangBaruTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        saveBaranfBaruButton = new javax.swing.JButton();
        namaBarangComboBox = new javax.swing.JComboBox<>();
        labelID = new javax.swing.JLabel();
        tglTransaksiTextFieldo = new datechooser.beans.DateChooserCombo();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Data Penjualan (Baru)");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 11, -1, -1));

        jLabel2.setText("Nama  :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 51, -1, -1));

        jLabel3.setText("Qty     :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 89, -1, -1));

        qtyBarangBaruTextField.setText(".....");
        getContentPane().add(qtyBarangBaruTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 86, 81, -1));

        jLabel4.setText("Satuan :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 89, -1, -1));

        satuanBaruComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kg", "Botol", "Box" }));
        getContentPane().add(satuanBaruComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 86, -1, -1));

        jLabel5.setText("Harga Beli :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 145, -1, -1));

        jLabel6.setText("Harga Jual :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 183, -1, -1));

        jLabel7.setText("Rp");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 145, -1, -1));

        jLabel8.setText("Rp");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 183, -1, -1));

        hargaBeliBarangBaruTextField.setText(".....");
        getContentPane().add(hargaBeliBarangBaruTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 142, 114, -1));

        hargaJualBarangBaruTextField.setText(".....");
        getContentPane().add(hargaJualBarangBaruTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 180, 114, -1));

        jLabel9.setText("Tgl Transaksi :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 230, -1, -1));

        saveBaranfBaruButton.setText("save");
        saveBaranfBaruButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBaranfBaruButtonActionPerformed(evt);
            }
        });
        getContentPane().add(saveBaranfBaruButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));

        namaBarangComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        namaBarangComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                namaBarangComboBoxItemStateChanged(evt);
            }
        });
        getContentPane().add(namaBarangComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 190, -1));

        labelID.setText("ID");
        getContentPane().add(labelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        tglTransaksiTextFieldo.setCurrentView(new datechooser.view.appearance.AppearancesList("Bordered",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    tglTransaksiTextFieldo.setLocale(new java.util.Locale("en", "GB", ""));
    getContentPane().add(tglTransaksiTextFieldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveBaranfBaruButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBaranfBaruButtonActionPerformed
        try {
            // TODO add your handling code here
            // seelum save/update periksa dulu button ini
            Penjualan penjualanBaru = new Penjualan();
            penjualanBaru.setNama(namaBarangComboBox.getSelectedItem()+"");
            int nilaiQty = Integer.parseInt(qtyBarangBaruTextField.getText());
            penjualanBaru.setSatuan(satuanBaruComboBox.getSelectedItem().toString());
            double nilaiHargaBeli = Double.parseDouble(hargaBeliBarangBaruTextField.getText());
            double nilaiHargaJual = Double.parseDouble(hargaJualBarangBaruTextField.getText());
            penjualanBaru.setHargaJual(nilaiHargaJual);
            penjualanBaru.setHargaBeli(nilaiHargaBeli);
            penjualanBaru.setQty(nilaiQty);
            
            
            String tglText = tglTransaksiTextFieldo.getText();
            Date date1 =  new SimpleDateFormat("dd/MM/yy").parse(tglText);
            tglText = new SimpleDateFormat("yyyy-MM-dd").format(date1);
            
            penjualanBaru.setTglTransaksi(tglText);
            DataBaseOperation engine = new DataBaseOperation();
            int noID = 0;
            
            
            if (saveBaranfBaruButton.getText().equalsIgnoreCase("save")) {
                
                
                engine.addDataPenjualan(penjualanBaru);
                engine.kurangiKuantitiBarang(penjualanBaru);
                System.out.println("Data Berhasil Tersimpan");
            } else {
                
                noID = Integer.parseInt(labelID.getText());
                engine.updateDataPenjualan(penjualanBaru,noID);
                
                System.out.println("Data Berhasil Terupdate");
            }
            
            
            
            window.refreshTabel();
            this.dispose();
        } catch (Exception ex) {
            System.out.println("terjadi kesalahan saat konversi");
            ex.printStackTrace();
        }
    
    }//GEN-LAST:event_saveBaranfBaruButtonActionPerformed

    private void namaBarangComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_namaBarangComboBoxItemStateChanged
        // TODO add your handling code here:
        
        String namadiperoleh ;
        if (namaBarangComboBox.getSelectedItem() != null){
            namadiperoleh = namaBarangComboBox.getSelectedItem().toString();
            
             DataBaseOperation engine = new DataBaseOperation();
        Barang datadidapat = engine.getBarang(namadiperoleh);
        
        hargaBeliBarangBaruTextField.setText(datadidapat.getHargaBeli()+"");
        hargaJualBarangBaruTextField.setText(datadidapat.getHargaJual()+"");
        }
        
               
        
    }//GEN-LAST:event_namaBarangComboBoxItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataPenjualanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataPenjualanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataPenjualanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataPenjualanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataPenjualanFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField hargaBeliBarangBaruTextField;
    private javax.swing.JTextField hargaJualBarangBaruTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelID;
    private javax.swing.JComboBox<String> namaBarangComboBox;
    private javax.swing.JTextField qtyBarangBaruTextField;
    private javax.swing.JComboBox<String> satuanBaruComboBox;
    private javax.swing.JButton saveBaranfBaruButton;
    private datechooser.beans.DateChooserCombo tglTransaksiTextFieldo;
    // End of variables declaration//GEN-END:variables
}
