/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package herbalsisteminventory;

import controller.DataBaseOperation;
import objekData.Barang;
import objekData.User;

/**
 *
 * @author HP
 */
public class DataBarangFrame extends javax.swing.JFrame {

    /**
     * Creates new form DataBarangFrame
     */
    public DataBarangFrame() {
        initComponents();
    }
    int angka;
    MainFrame windowMainFrame = null ;
    
    public void setMainFrame(MainFrame frameMasuk){
        windowMainFrame = frameMasuk ;
        
    }

    public void terimaData(Barang dataMasuk, int noID) {
        namaBarangBaruTextField.setText(dataMasuk.getNama());
        satuanComboBox.setSelectedItem(dataMasuk.getSatuan());
        qtyBarangBaruTextField.setText(dataMasuk.getQty() + "");
        hargaBeliBaruTextField.setText(dataMasuk.getHargaBeli() + "");
        hargaJualBarangBaruTextField.setText(dataMasuk.getHargaJual() + "");
        saveBarangBaruButton.setText("Update");
        labelID.setText(noID+"");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        namaBarangBaruTextField = new javax.swing.JTextField();
        qtyBarangBaruTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        satuanComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        hargaBeliBaruTextField = new javax.swing.JTextField();
        hargaJualBarangBaruTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        saveBarangBaruButton = new javax.swing.JButton();
        labelID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Data Barang (Baru)");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 11, -1, -1));

        jLabel2.setText("Nama :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 39, -1, -1));

        jLabel3.setText("Qty    :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 70, -1, -1));

        namaBarangBaruTextField.setText(".....");
        getContentPane().add(namaBarangBaruTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 36, 175, -1));

        qtyBarangBaruTextField.setText(".....");
        qtyBarangBaruTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyBarangBaruTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(qtyBarangBaruTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 67, 102, -1));

        jLabel4.setText("Satuan : ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 70, -1, -1));

        satuanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kg", "Botol", "Box" }));
        getContentPane().add(satuanComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 67, -1, -1));

        jLabel5.setText("Harga Beli  :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 151, -1, -1));

        jLabel6.setText("Harga Jual :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 189, -1, -1));

        hargaBeliBaruTextField.setText(".....");
        getContentPane().add(hargaBeliBaruTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 148, 102, -1));

        hargaJualBarangBaruTextField.setText(".....");
        getContentPane().add(hargaJualBarangBaruTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 186, 102, -1));

        jLabel7.setText("Rp");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 151, -1, -1));

        jLabel8.setText("Rp");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 189, -1, -1));

        saveBarangBaruButton.setText("Save");
        saveBarangBaruButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBarangBaruButtonActionPerformed(evt);
            }
        });
        getContentPane().add(saveBarangBaruButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 236, -1, -1));

        labelID.setText("ID");
        getContentPane().add(labelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void qtyBarangBaruTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyBarangBaruTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyBarangBaruTextFieldActionPerformed

    private void saveBarangBaruButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBarangBaruButtonActionPerformed
        // seelum save/update periksa dulu button ini
        Barang barangBaru = new Barang();
        barangBaru.setNama(namaBarangBaruTextField.getText());
        barangBaru.setSatuan(satuanComboBox.getSelectedItem().toString());
        double nilaiHargaBeli = Double.parseDouble(hargaBeliBaruTextField.getText());
        double nilaiHargaJual = Double.parseDouble(hargaJualBarangBaruTextField.getText());
        int nilaiQty = Integer.parseInt(qtyBarangBaruTextField.getText());
        barangBaru.setHargaJual(nilaiHargaJual);
        barangBaru.setHargaBeli(nilaiHargaBeli);
        barangBaru.setQty(nilaiQty);
        DataBaseOperation engine = new DataBaseOperation();
             
        if (saveBarangBaruButton.getText().equalsIgnoreCase("save")) {

       
            engine.addDataBarang(barangBaru);

            System.out.println("Data Berhasil Tersimpan");
        } else {
            
            int noID = Integer.parseInt(labelID.getText());
            
            engine.updateDataBarang(barangBaru,noID);

            System.out.println("Data Berhasil Terupdate");
        }
        windowMainFrame.refreshTabel();
        this.dispose();

    }//GEN-LAST:event_saveBarangBaruButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataBarangFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataBarangFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataBarangFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataBarangFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataBarangFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField hargaBeliBaruTextField;
    private javax.swing.JTextField hargaJualBarangBaruTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel labelID;
    private javax.swing.JTextField namaBarangBaruTextField;
    private javax.swing.JTextField qtyBarangBaruTextField;
    private javax.swing.JComboBox<String> satuanComboBox;
    private javax.swing.JButton saveBarangBaruButton;
    // End of variables declaration//GEN-END:variables
}
