/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package herbalsisteminventory;

import controller.DataBaseOperation;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import objekData.User;

/**
 *
 * @author HP
 */
public class DataUserFrame extends javax.swing.JFrame {

    /**
     * Creates new form DataUserFrame
     */
    public DataUserFrame() {
        initComponents();
    }
    
        int angka;
    MainFrame windowMainFrame = null ;
    
    public void setMainFrame(MainFrame frameMasuk){
        windowMainFrame = frameMasuk ;
        
    }
    
    public void terimaData( User dataMasuk, int noID) {
    usernameDataBarTextFIELD.setText(dataMasuk.getUsername());
    passwordDataBarTextField.setText(dataMasuk.getPassword());
    tglBuatDataBarTextField.setText(dataMasuk.getTglBuat()+ "");
    userTypeComboBox.setSelectedItem(dataMasuk.getUsertype()+ "");
    saveDataBaruButton.setText("Update");
    labelID.setText(noID+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        usernameDataBarTextFIELD = new javax.swing.JTextField();
        passwordDataBarTextField = new javax.swing.JTextField();
        userTypeComboBox = new javax.swing.JComboBox<>();
        emailDataBarTextField = new javax.swing.JTextField();
        saveDataBaruButton = new javax.swing.JButton();
        labelID = new javax.swing.JLabel();
        panelSetiingAdmin = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        dataBarangCheckBox = new javax.swing.JCheckBox();
        dataPenjualanCheckBox = new javax.swing.JCheckBox();
        dataPelangganCheckBox = new javax.swing.JCheckBox();
        tglBuatDataBarTextField = new datechooser.beans.DateChooserCombo();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 51));

        jLabel1.setText("Data User (Baru)");

        jLabel2.setText("Username :");

        jLabel3.setText("Password :");

        jLabel4.setText("User Type :");

        jLabel5.setText("Email :");

        jLabel6.setText("Tgl Pembuatan :");

        usernameDataBarTextFIELD.setText(".....");

        passwordDataBarTextField.setText(".....");

        userTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Warehouse", "Sales" }));
        userTypeComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                userTypeComboBoxItemStateChanged(evt);
            }
        });

        emailDataBarTextField.setText(".....");

        saveDataBaruButton.setText("Save");
        saveDataBaruButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveDataBaruButtonActionPerformed(evt);
            }
        });

        labelID.setText("ID");

        jLabel22.setText("Administator");

        jLabel23.setText("Allow Staff to Manage :");

        dataBarangCheckBox.setText("Data Barang");
        dataBarangCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataBarangCheckBoxActionPerformed(evt);
            }
        });

        dataPenjualanCheckBox.setText("Data Penjualan");

        dataPelangganCheckBox.setText("Data Pelanggan");

        javax.swing.GroupLayout panelSetiingAdminLayout = new javax.swing.GroupLayout(panelSetiingAdmin);
        panelSetiingAdmin.setLayout(panelSetiingAdminLayout);
        panelSetiingAdminLayout.setHorizontalGroup(
            panelSetiingAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSetiingAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSetiingAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addGroup(panelSetiingAdminLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelSetiingAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataPenjualanCheckBox)
                            .addGroup(panelSetiingAdminLayout.createSequentialGroup()
                                .addComponent(dataBarangCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(dataPelangganCheckBox)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        panelSetiingAdminLayout.setVerticalGroup(
            panelSetiingAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSetiingAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addGroup(panelSetiingAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(dataBarangCheckBox)
                    .addComponent(dataPelangganCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dataPenjualanCheckBox)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        tglBuatDataBarTextField.setCurrentView(new datechooser.view.appearance.AppearancesList("Bordered",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    tglBuatDataBarTextField.setFormat(1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(44, 44, 44)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6))
                    .addGap(37, 37, 37)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tglBuatDataBarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(emailDataBarTextField)))
                .addComponent(jLabel1)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4))
                    .addGap(59, 59, 59)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(userTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(usernameDataBarTextFIELD, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                        .addComponent(passwordDataBarTextField))))
            .addGap(166, 166, 166)
            .addComponent(labelID)
            .addGap(50, 50, 50))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(panelSetiingAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(saveDataBaruButton))
            .addGap(76, 76, 76))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(labelID))
            .addGap(25, 25, 25)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(usernameDataBarTextFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(passwordDataBarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(userTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(41, 41, 41)
                    .addComponent(jLabel5))
                .addComponent(emailDataBarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel6)
                .addComponent(tglBuatDataBarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addComponent(saveDataBaruButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(panelSetiingAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(63, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveDataBaruButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveDataBaruButtonActionPerformed
        
        try {
            User orangBaru = new User();
            orangBaru.setUsername(usernameDataBarTextFIELD.getText());
            orangBaru.setPassword(passwordDataBarTextField.getText());
            
            String tanggalBaru = tglBuatDataBarTextField.getText();
            
            
            Date date1 =  new SimpleDateFormat("MMM d, yyyy").parse(tanggalBaru);
            tanggalBaru = new SimpleDateFormat("yyyy-MM-dd").format(date1);
            
            
            orangBaru.setTglBuat(tanggalBaru);
            orangBaru.setUsertype(userTypeComboBox.getSelectedItem().toString());
            orangBaru.setAksesDataBarang(dataBarangCheckBox.isSelected());
            orangBaru.setAksesDataPelanggan(dataPelangganCheckBox.isSelected());
            orangBaru.setAksesDataPenjualan(dataPenjualanCheckBox.isSelected());
            
            DataBaseOperation engine = new DataBaseOperation();
            
            if (saveDataBaruButton.getText().equalsIgnoreCase("save")) {
                
                
                engine.addDataUser(orangBaru);
                
                System.out.println("Data Berhasil Tersimpan");
            } else {
                
                int noID = Integer.parseInt(labelID.getText());
                
                engine.updateDataUser(orangBaru,noID);
                
                System.out.println("Data Berhasil Terupdate");
            }
            
            windowMainFrame.refreshTabel();
            this.dispose();
            
            System.out.println("Data Berhasil Tersimpan");
        } catch (ParseException ex) {
            Logger.getLogger(DataUserFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveDataBaruButtonActionPerformed

    private void dataBarangCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataBarangCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataBarangCheckBoxActionPerformed

    private void userTypeComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_userTypeComboBoxItemStateChanged
       String jenis = userTypeComboBox.getSelectedItem().toString();
       
        if (jenis.equalsIgnoreCase("admin")){
            dataBarangCheckBox.setSelected(true);
            dataPenjualanCheckBox.setSelected(true);
            dataPelangganCheckBox.setSelected(true);
        } else if (jenis.equalsIgnoreCase("sales")){
            dataBarangCheckBox.setSelected(false);
            dataPenjualanCheckBox.setSelected(true);
            dataPelangganCheckBox.setSelected(true);
        } else if (jenis.equalsIgnoreCase("warehouse")){
            dataBarangCheckBox.setSelected(true);
            dataPenjualanCheckBox.setSelected(false);
            dataPelangganCheckBox.setSelected(false);
        }
    
    }//GEN-LAST:event_userTypeComboBoxItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataUserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataUserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataUserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataUserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataUserFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox dataBarangCheckBox;
    private javax.swing.JCheckBox dataPelangganCheckBox;
    private javax.swing.JCheckBox dataPenjualanCheckBox;
    private javax.swing.JTextField emailDataBarTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel labelID;
    private javax.swing.JPanel panelSetiingAdmin;
    private javax.swing.JTextField passwordDataBarTextField;
    private javax.swing.JButton saveDataBaruButton;
    private datechooser.beans.DateChooserCombo tglBuatDataBarTextField;
    private javax.swing.JComboBox<String> userTypeComboBox;
    private javax.swing.JTextField usernameDataBarTextFIELD;
    // End of variables declaration//GEN-END:variables
}
